server.port=10102
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

jwt.secret=shop-jwt-secret-key-for-authentication-2024
jwt.expiration=86400000

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
